# Generated by Django 3.2.7 on 2021-09-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='procedure',
            field=models.TextField(default='None'),
        ),
    ]
